# Site settings
title: 靳宝合
description: 一个超级大学渣.
cover: https://github.com/Flyme-jin/flyme-jin.github.io/blob/master/assets/images/radhakrishna.jpg
logo: https://github.com/Flyme-jin/flyme-jin.github.io/blob/master/assets/images/logo.png
favicon: https://github.com/Flyme-jin/flyme-jin.github.io/blob/master/assets/images/favicon.png
baseurl: "/hanuman/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://flyme-jin.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: flyme-jin
twitter: twitter
github:  flyme-jin

#Additional Pages
about: about
contact: 18902016110
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: flyme-jin #github username
repo: flyme-jin.io #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/flyme-jin/flyme-jin.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
